# Generated by Django 5.0.6 on 2024-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_recommander', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicited_areaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recommanded_area', models.CharField(max_length=200)),
                ('cluster', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
