# Generated by Django 5.0.6 on 2024-06-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_recommander', '0004_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Predicited_areaMap',
        ),
    ]
